name: Script Linter
on: [push]
jobs:
  Script-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Translation
        uses: actions/checkout@v2
        with:
          path: translation
      - name: Checkout deepLuna
        uses: actions/checkout@v2
        with:
          repository: Hakanaou/deepLuna
          path: deepluna
      - name: Lint
        run: ${{ github.workspace }}/deepluna/luna_linter.py --db-path ${{ github.workspace }}/translation/scene_map.json --script-path ${{ github.workspace }}/translation/script/
